version: '3.0'

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: yarn dev
    restart: always
